baseURL: 'https://yangoos57.github.io/'
googleAnalytics: G-K109LYQBX3
DisqusShortname: yangoos92
pluralizelisttitles: "false"
relativeURLs: true
canonifyURLs: true
title: Leeway
paginate: '5'
summaryLength: '20'
enableEmoji: true
preserveTaxonomyNames: true
enableRobotsTXT: true

related:
  includeNewer: true
  indices:
  - name: image
    weight: 100
  - name: Tags
    weight: 50
  threshold: 50
  toLower: false


taxonomies:
  tags : Tags

params:
  plugins:
    js:
      - link: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js'
    css: 
      # - link: ''
  Github: 'https://github.com/yangoos57'
  
  logo: images/icon/icon.webp
  logo_width: 100px
  favicon: images/icon/icon.webp
  description: '데이터 관리'
  icon_font: Fontawesome 5 Free
  cookies:
    enable: false
    expire_days: 2

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true ## 초기값 false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: monokai
    tabWidth: 3
  tableOfContents:
    endLevel: 6
    startLevel: 2