baseURL: 'https://yangoos57.github.io/'
relativeURLs: true
canonifyURLs: true
title: Yangoos Archive
# theme: Cupper
paginate: '5'
summaryLength: '20'
googleAnalytics: ''
disqusShortname: ''

preserveTaxonomyNames: true

taxonomies:
  category: Category
  python: Python
  personal: Personal
  data_analytics: Data_Analytics

params:
  plugins:
    js:
      - link: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js'
    css: 
      # - link: ''

  logo: images/logo.png
  logo_width: 100px
  favicon: images/favicon.png
  description: This is meta description

  copyright: 'Designed & Developed By [Gethugothemes](https://gethugothemes.com/)'
  custom_script: ''
  variables:
    primary_color: '#33186D'
    body_color: '#fff'
    text_color: '#333'
    text_color_dark: '#000'
    text_color_light: '#999'
    border_color: '#e2e2e2'
    black: '#000'
    white: '#fff'
    light: '#f1f1f1'
    primary_font: 'DM Sans:400,500,700'
    icon_font: Fontawesome 5 Free
  cookies:
    enable: false
    expire_days: 2
    


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true ## 초기값 false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: monokai
    tabWidth: 3
  tableOfContents:
    endLevel: 6
    startLevel: 2