baseURL: https://yangoos57.github.io
languageCode: en-us
defaultContentLanguage: en
title: Hello world!
theme: Cupper
googleAnalytics: UA-218073068-1
disqusShortname: yangoos92
enableGitInfo: true 

taxonomies:
  tag: tags
  category : categories
  subcategory : subcategories

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: description 
  homeMetaContent: Hommetacontent
  footer: footer
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  # defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: An alternative text description of the logo
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js
  # themeVariant: cupper ## D:\git_local_repository\hugo_blog\static\css 폰트 바꾸기 위한 css

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /posts/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5
    - name: category
      url: /categories/
      weight: 6
    - name: python
      url: /posts/python/

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false ## 초기값 false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
