baseURL: https://yangoos57.github.io
relativeURLs: true
canonifyURLs: true
languageCode: en-us
defaultContentLanguage: en
title: Hello world!
theme: Cupper
googleAnalytics: UA-218073068-1
disqusShortname: yangoos92
enableGitInfo: true 

taxonomies:
  python : python
  Data_analytics : Data_analytics
  Personal : Personal

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: description 
  homeMetaContent: Hommetacontent
  footer: footer
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  # defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: An alternative text description of the logo
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js
  # themeVariant: cupper ## D:\git_local_repository\hugo_blog\static\css 폰트 바꾸기 위한 css

menu:
  nav:
    - name: Seaborn_menu
      url: /python/Seaborn_tag
      weight: 1
    - name: pandas_menu
      url: /python/pandas
      weight: 2
    - name: 기본함수
      url: /python/기본함수
      weight: 3
    - name: 데이터 분석 이론
      url: /Data_analytics/데이터 분석 이론
      weight: 4
    - name: 분석 실무
      url: /Data_analytics/분석 실무
      weight: 5
    - name: 데이터 전처리
      url: /Data_analytics/데이터 전처리
      weight: 6
    - name: 끄적끄적
      url: /Personal/끄적끄적
      weight: 7


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true ## 초기값 false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: monokai
    tabWidth: 3
  tableOfContents:
    endLevel: 6
    startLevel: 2
